apiVersion: v1
kind: Service
metadata:
  name: test-app-svc
spec:
  type: NodePort
  selector:
    app: test-app
  ports:
    - name: test-app
      port: 8000
      targetPort: 8000
      nodePort: 30080